import { StyleSheet } from "react-native";
import { T } from "@/src/theme";

/** Styles partagés par l'écran Compte et ses sous-composants admin. */
export const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: T.color.surface },
  header: {
    backgroundColor: T.color.surfaceSecondary,
    borderBottomWidth: 0.5,
    borderBottomColor: T.color.border,
    paddingBottom: T.space.md,
  },
  title: { fontSize: T.font.xxl, fontWeight: "800", color: T.color.onSurface, paddingHorizontal: T.space.lg },
  card: {
    backgroundColor: T.color.surfaceSecondary,
    borderRadius: T.radius.md,
    padding: T.space.lg,
    marginBottom: T.space.md,
    ...T.shadow.card,
  },
  sessionRow: { flexDirection: "row", alignItems: "center", gap: T.space.md },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: T.color.brandSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  sessionTitle: { fontSize: T.font.lg, fontWeight: "700", color: T.color.onSurface },
  sessionSub: { fontSize: T.font.base, color: T.color.muted, marginTop: 2 },
  sessionExpiry: { fontSize: T.font.sm, color: T.color.brand, marginTop: 4, fontWeight: "600" },
  sectionLabel: {
    fontSize: T.font.sm,
    fontWeight: "700",
    color: T.color.muted,
    letterSpacing: 0.5,
    marginTop: T.space.md,
    marginBottom: T.space.sm,
    paddingHorizontal: 2,
  },
  cardTitle: { fontSize: T.font.lg, fontWeight: "700", color: T.color.onSurface },
  cardSub: { fontSize: T.font.base, color: T.color.muted, marginTop: 4, marginBottom: T.space.sm },
  input: {
    backgroundColor: T.color.surfaceTertiary,
    borderRadius: T.radius.md,
    paddingHorizontal: T.space.md,
    paddingVertical: 13,
    fontSize: T.font.base,
    color: T.color.onSurface,
    marginTop: T.space.md,
  },
  err: { color: T.color.error, fontSize: T.font.base, marginTop: T.space.sm },
  primaryBtn: {
    flexDirection: "row",
    gap: 6,
    backgroundColor: T.color.brand,
    borderRadius: T.radius.md,
    paddingVertical: 14,
    alignItems: "center",
    justifyContent: "center",
    marginTop: T.space.md,
  },
  primaryBtnTxt: { color: "#fff", fontWeight: "800", fontSize: T.font.base },
  cfgRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: T.space.sm,
  },
  cfgLabel: { fontSize: T.font.base, color: T.color.onSurface, fontWeight: "600", flex: 1 },
  cfgStepper: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: T.color.surfaceTertiary,
    borderRadius: T.radius.md,
    padding: 3,
  },
  stepBtn: {
    width: 34,
    height: 34,
    borderRadius: T.radius.sm,
    backgroundColor: T.color.surfaceSecondary,
    alignItems: "center",
    justifyContent: "center",
  },
  cfgVal: { minWidth: 52, textAlign: "center", fontWeight: "800", fontSize: T.font.base, color: T.color.onSurface },
  cfgHint: { fontSize: T.font.sm, color: T.color.muted, marginTop: T.space.sm, fontWeight: "600" },
  cfgDivider: { height: 0.5, backgroundColor: T.color.border, marginVertical: T.space.md },
  alertCard: {
    backgroundColor: "#FFF7ED",
    borderRadius: T.radius.md,
    borderWidth: 1,
    borderColor: "#FDBA74",
    padding: T.space.lg,
    marginBottom: T.space.md,
  },
  alertHead: { flexDirection: "row", alignItems: "center", gap: 6 },
  alertTitle: { fontSize: T.font.base, fontWeight: "800", color: "#B45309", flex: 1 },
  alertSub: { fontSize: T.font.sm, color: "#9A3412", marginTop: 4, marginBottom: T.space.sm },
  alertBtns: { flexDirection: "row", flexWrap: "wrap", gap: T.space.sm, marginTop: 4 },
  alertBlockBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: "#DC2626",
    borderRadius: T.radius.md,
    paddingVertical: 10,
    paddingHorizontal: T.space.md,
  },
  alertBlockTxt: { color: "#fff", fontWeight: "700", fontSize: T.font.sm },
  alertRevokeBtn: {
    borderWidth: 1,
    borderColor: "#B45309",
    borderRadius: T.radius.md,
    paddingVertical: 10,
    paddingHorizontal: T.space.md,
    justifyContent: "center",
  },
  alertRevokeTxt: { color: "#B45309", fontWeight: "700", fontSize: T.font.sm },
  noAlert: {
    fontSize: T.font.base,
    color: T.color.brand,
    fontWeight: "600",
    marginBottom: T.space.md,
    paddingHorizontal: 2,
  },
  codeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: T.space.sm,
    backgroundColor: T.color.surfaceSecondary,
    borderRadius: T.radius.md,
    padding: T.space.md,
    marginBottom: T.space.sm,
    ...T.shadow.card,
  },
  codeVal: { fontSize: T.font.lg, fontWeight: "800", color: T.color.onSurface, letterSpacing: 2 },
  codeMeta: { fontSize: T.font.sm, color: T.color.muted, marginTop: 2 },
  codeExpiry: { fontSize: T.font.sm, color: T.color.onSurfaceTertiary, marginTop: 2, fontWeight: "600" },
  expiryLabel: { fontSize: T.font.sm, fontWeight: "700", color: T.color.muted, marginTop: T.space.md },
  expChip: {
    flexGrow: 1,
    alignItems: "center",
    paddingVertical: 10,
    borderRadius: T.radius.md,
    backgroundColor: T.color.surfaceTertiary,
  },
  expChipActive: { backgroundColor: T.color.brand },
  expChipTxt: { color: T.color.onSurfaceTertiary, fontWeight: "700", fontSize: T.font.sm },
  expChipTxtActive: { color: "#fff" },
  statusPill: { paddingHorizontal: 10, paddingVertical: 4, borderRadius: T.radius.pill },
  statusOn: { backgroundColor: T.color.brandSecondary },
  statusOff: { backgroundColor: T.color.surfaceTertiary },
  statusTxt: { fontSize: T.font.sm, fontWeight: "700" },
  toggleBtn: { padding: 2 },
  devStatsRow: {
    flexDirection: "row",
    marginBottom: T.space.md,
    borderBottomWidth: 0.5,
    borderBottomColor: T.color.border,
    paddingBottom: T.space.md,
  },
  devStat: { flex: 1, alignItems: "center", gap: 2 },
  devStatVal: { fontSize: T.font.xl, fontWeight: "800", color: T.color.onSurface },
  devStatLbl: { fontSize: T.font.sm, color: T.color.muted },
  devRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: T.space.md,
    paddingVertical: 8,
    borderTopWidth: 0.5,
    borderTopColor: T.color.border,
  },
  devName: { fontSize: T.font.base, fontWeight: "700", color: T.color.onSurface },
  devMeta: { fontSize: T.font.sm, color: T.color.muted, marginTop: 1 },
  devSeen: { fontSize: T.font.sm, color: T.color.brand, marginTop: 1, fontWeight: "600" },
  devBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: T.radius.sm },
  devBtnBlock: { backgroundColor: "#FEE2E2" },
  devBtnUnblock: { backgroundColor: T.color.brandSecondary },
  devBtnTxt: { fontSize: T.font.sm, fontWeight: "800" },
  freeHead: { flexDirection: "row", alignItems: "center", gap: T.space.sm },
  dot: { width: 12, height: 12, borderRadius: 6 },
  durRow: { flexDirection: "row", gap: T.space.sm, marginTop: T.space.md, flexWrap: "wrap" },
  durChip: {
    flexGrow: 1,
    alignItems: "center",
    paddingVertical: 12,
    borderRadius: T.radius.md,
    backgroundColor: T.color.brandSecondary,
  },
  durTxt: { color: T.color.brand, fontWeight: "800", fontSize: T.font.base },
  disableBtn: {
    flexDirection: "row",
    gap: 6,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 12,
    marginTop: T.space.md,
    borderRadius: T.radius.md,
    backgroundColor: "#FEE2E2",
  },
  disableTxt: { color: T.color.error, fontWeight: "800", fontSize: T.font.base },
  logoutBtn: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FEE2E2",
    borderRadius: T.radius.md,
    paddingVertical: 14,
    marginTop: T.space.lg,
  },
  logoutTxt: { color: T.color.error, fontWeight: "800", fontSize: T.font.base },
});

export type AnalysisCfg = {
  favoriMax: number;
  outsiderMax: number;
  baisseSeuil: number;
  scoreMinJouer: number;
};


################################################################################
